
package relational.operators;

public class RelationalOperators {

   
    public static void main(String[] args) {
        System.out.println(10<20);//This will give a boolean output..Either true or false..Less than operator..
        System.out.println(10>20);//Same as previous..Greater than operator..
        System.out.println(10==20);//Same as previous..Equality operator...
        System.out.println(10!=20);//Same as previous..Inequality operator...
        System.out.println(10<=20);//Same as previous..Less than or equal operator...
        System.out.println(10>=20);//Same as previous..Greater than or equal operator...
        System.out.println(123+456<987-654);//A expression containing operators
        System.out.println("hello".equals("hello")); //Sting Comparison:Instead of using = sign,we use equals method here....
        System.out.println("hello".equals("hi")); //Same as above..Outputs a boolean result....
    }
    
}
