
package datatypes;

public class DataTypes {

    public static void main(String[] args) {
        System.out.println("hello"); //string
        System.out.println(10); //number
        System.out.println(123456789123456L); //it is a long int.........normal int goes up to 2147483647.....
        System.out.println(3.1415); //Double Precision number:The standard floating point number type in JAVA is called double...
        System.out.println(3.1415F);//Floating point number...LEss precsion than double....
        System.out.println(true);//A boolean value.Either true or false......
        System.out.println(false);//Boolean value...
    }
    
}
